header:
    title: Welcome to ITslang!
    text: Java courses in English
    button: Tell Me More
    buttonlink: "#timeline" # "#{section}" or "URL/page link"

services:
    title: "Why IT?"
    text: ""
    section: services
    list:
      - title: "Perspective"
        desc: "No career boundaries - <b>IT</b> specialist is paid as much as he deserves."
        icon: fas fa-seedling #find more at https://fontawesome.com/icons
      - title: "Demand"
        desc: "<b>IT</b> is a popular field and the demand for specialists grows from year to year."
        icon: fas fa-globe
      - title: "Development"
        desc: "<b>IT</b> is very dynamic field encouraging continuous self-development."
        icon: fas fa-brain
      - title: "Interesting Job"
        desc: "<b>IT</b> is interesting and fun - you will not be bored.<br>😄"
        icon: fas fa-code
      - title: "High Pay"
        desc: "<b>IT</b> sector is one of the highly paid on the market."
        icon: fas fa-coins
      - title: "Remote"
        desc: "<b>IT</b> provides possibility to work remotely from anywhere in the world."
        icon: fas fa-laptop-code

timeline:
    title: "About us"
    text: "We will be your guide along this path:"
    section: timeline
    events:
      - title: "<br>Beginner"
        #year: "2009-2011"
        desc: "Basic programing concepts:<br>Procedural Java"
        image: assets/img/timeline/1.jpg
        alt:
        align: left
      - title: "<br>Middle"
        #year: "March 2011"
        desc: "Object-oriented programing:<br>Java SE"
        image: assets/img/timeline/2.jpg
        alt:
        align: right
      - title: "<br>Advanced"
        #year: "2019"
        desc: "Enterprise Frameworks:<br>Professional Java"
        image: assets/img/timeline/3.jpg
        alt: image alt text
        #align: #default is left
    end: "Join Us! <br> Go to <br> IT!"

portfolio:
    title: "Courses"
#    text: "Lorem ipsum dolor sit amet consectetur."
    section: portfolio

contact:
    title: "Contact Us"
#    text: "Lorem ipsum or call 123456789"
    section: contact
    
footer:
    legal: "Privacy Policy"
    social:
      - url: mailto:itslang.school@gmail.com
        icon: "far fa-envelope"
      - url: https://join.skype.com/invite/hE28sQiVt15l
        icon: "fab fa-skype"
      - url: https://facebook.com
        icon: "fab fa-facebook-f"
      - url: https://instagram.com
        icon: "fab fa-instagram"
      - url: https://github.com/itslang
        icon: "fab fa-github"


# {{ site.data.sitetext.ex.ex | markdownify | default: example }}
